// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.0
// 	protoc        v3.21.12
// source: public/proto/base.proto

package base

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 定义bool类型的查询枚举
type BoolSelectEnum int32

const (
	BoolSelectEnum_TRUE  BoolSelectEnum = 0
	BoolSelectEnum_FALSE BoolSelectEnum = 1
	BoolSelectEnum_ALL   BoolSelectEnum = 2
)

// Enum value maps for BoolSelectEnum.
var (
	BoolSelectEnum_name = map[int32]string{
		0: "TRUE",
		1: "FALSE",
		2: "ALL",
	}
	BoolSelectEnum_value = map[string]int32{
		"TRUE":  0,
		"FALSE": 1,
		"ALL":   2,
	}
)

func (x BoolSelectEnum) Enum() *BoolSelectEnum {
	p := new(BoolSelectEnum)
	*p = x
	return p
}

func (x BoolSelectEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BoolSelectEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_public_proto_base_proto_enumTypes[0].Descriptor()
}

func (BoolSelectEnum) Type() protoreflect.EnumType {
	return &file_public_proto_base_proto_enumTypes[0]
}

func (x BoolSelectEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BoolSelectEnum.Descriptor instead.
func (BoolSelectEnum) EnumDescriptor() ([]byte, []int) {
	return file_public_proto_base_proto_rawDescGZIP(), []int{0}
}

var File_public_proto_base_proto protoreflect.FileDescriptor

var file_public_proto_base_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62,
	0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2a, 0x2e, 0x0a, 0x0e, 0x42, 0x6f, 0x6f, 0x6c, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x45, 0x6e,
	0x75, 0x6d, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x52, 0x55, 0x45, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05,
	0x46, 0x41, 0x4c, 0x53, 0x45, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x4c, 0x4c, 0x10, 0x02,
	0x42, 0x13, 0x5a, 0x11, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x3b, 0x62, 0x61, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_public_proto_base_proto_rawDescOnce sync.Once
	file_public_proto_base_proto_rawDescData = file_public_proto_base_proto_rawDesc
)

func file_public_proto_base_proto_rawDescGZIP() []byte {
	file_public_proto_base_proto_rawDescOnce.Do(func() {
		file_public_proto_base_proto_rawDescData = protoimpl.X.CompressGZIP(file_public_proto_base_proto_rawDescData)
	})
	return file_public_proto_base_proto_rawDescData
}

var file_public_proto_base_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_public_proto_base_proto_goTypes = []interface{}{
	(BoolSelectEnum)(0), // 0: proto.BoolSelectEnum
}
var file_public_proto_base_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_public_proto_base_proto_init() }
func file_public_proto_base_proto_init() {
	if File_public_proto_base_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_public_proto_base_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_public_proto_base_proto_goTypes,
		DependencyIndexes: file_public_proto_base_proto_depIdxs,
		EnumInfos:         file_public_proto_base_proto_enumTypes,
	}.Build()
	File_public_proto_base_proto = out.File
	file_public_proto_base_proto_rawDesc = nil
	file_public_proto_base_proto_goTypes = nil
	file_public_proto_base_proto_depIdxs = nil
}
