// protoc --go_out=. --go-grpc_out=require_unimplemented_servers=false:. ./common/user/rpc/proto/*.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: common/user/rpc/proto/userGroup.proto

package userPB

import (
	proto "Goldfinger/public/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建用户组传入参数
type CreateUserGroupReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`          // 用户组名称
	ParentId int64  `protobuf:"varint,2,opt,name=ParentId,proto3" json:"ParentId,omitempty"` // 用户组父级ID，为0代表顶级组
}

func (x *CreateUserGroupReq) Reset() {
	*x = CreateUserGroupReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_user_rpc_proto_userGroup_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserGroupReq) ProtoMessage() {}

func (x *CreateUserGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_user_rpc_proto_userGroup_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserGroupReq.ProtoReflect.Descriptor instead.
func (*CreateUserGroupReq) Descriptor() ([]byte, []int) {
	return file_common_user_rpc_proto_userGroup_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserGroupReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserGroupReq) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

// 创建用户组返回参数
type CreateUserGroupResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"` // 新创建的用户组ID
}

func (x *CreateUserGroupResp) Reset() {
	*x = CreateUserGroupResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_user_rpc_proto_userGroup_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserGroupResp) ProtoMessage() {}

func (x *CreateUserGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_common_user_rpc_proto_userGroup_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserGroupResp.ProtoReflect.Descriptor instead.
func (*CreateUserGroupResp) Descriptor() ([]byte, []int) {
	return file_common_user_rpc_proto_userGroup_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserGroupResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 查询用户组详情传入参数
type RetrieveUserGroupReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"` // 用户组ID
}

func (x *RetrieveUserGroupReq) Reset() {
	*x = RetrieveUserGroupReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_user_rpc_proto_userGroup_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveUserGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveUserGroupReq) ProtoMessage() {}

func (x *RetrieveUserGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_user_rpc_proto_userGroup_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveUserGroupReq.ProtoReflect.Descriptor instead.
func (*RetrieveUserGroupReq) Descriptor() ([]byte, []int) {
	return file_common_user_rpc_proto_userGroup_proto_rawDescGZIP(), []int{2}
}

func (x *RetrieveUserGroupReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 查询用户组详情返回参数
type RetrieveUserGroupResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`                   // 用户组ID
	Name        string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`                // 用户组名称
	ParentId    int64  `protobuf:"varint,3,opt,name=ParentId,proto3" json:"ParentId,omitempty"`       // 用户组父级ID
	IsAdmin     bool   `protobuf:"varint,4,opt,name=IsAdmin,proto3" json:"IsAdmin,omitempty"`         // 是否管理员
	Desc        string `protobuf:"bytes,5,opt,name=Desc,proto3" json:"Desc,omitempty"`                // 备注
	CreateUser  int64  `protobuf:"varint,6,opt,name=CreateUser,proto3" json:"CreateUser,omitempty"`   // 创建用户ID
	UpdateUser  int64  `protobuf:"varint,7,opt,name=UpdateUser,proto3" json:"UpdateUser,omitempty"`   // 更新用户ID
	CreateGroup int64  `protobuf:"varint,8,opt,name=CreateGroup,proto3" json:"CreateGroup,omitempty"` // 创建用户组ID
	UpdateGroup int64  `protobuf:"varint,9,opt,name=UpdateGroup,proto3" json:"UpdateGroup,omitempty"` // 更新用户组ID
	CreateAt    int64  `protobuf:"varint,10,opt,name=CreateAt,proto3" json:"CreateAt,omitempty"`      // 创建时间
	UpdateAt    int64  `protobuf:"varint,11,opt,name=UpdateAt,proto3" json:"UpdateAt,omitempty"`      // 更新时间
}

func (x *RetrieveUserGroupResp) Reset() {
	*x = RetrieveUserGroupResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_user_rpc_proto_userGroup_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetrieveUserGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrieveUserGroupResp) ProtoMessage() {}

func (x *RetrieveUserGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_common_user_rpc_proto_userGroup_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrieveUserGroupResp.ProtoReflect.Descriptor instead.
func (*RetrieveUserGroupResp) Descriptor() ([]byte, []int) {
	return file_common_user_rpc_proto_userGroup_proto_rawDescGZIP(), []int{3}
}

func (x *RetrieveUserGroupResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RetrieveUserGroupResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RetrieveUserGroupResp) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *RetrieveUserGroupResp) GetIsAdmin() bool {
	if x != nil {
		return x.IsAdmin
	}
	return false
}

func (x *RetrieveUserGroupResp) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *RetrieveUserGroupResp) GetCreateUser() int64 {
	if x != nil {
		return x.CreateUser
	}
	return 0
}

func (x *RetrieveUserGroupResp) GetUpdateUser() int64 {
	if x != nil {
		return x.UpdateUser
	}
	return 0
}

func (x *RetrieveUserGroupResp) GetCreateGroup() int64 {
	if x != nil {
		return x.CreateGroup
	}
	return 0
}

func (x *RetrieveUserGroupResp) GetUpdateGroup() int64 {
	if x != nil {
		return x.UpdateGroup
	}
	return 0
}

func (x *RetrieveUserGroupResp) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *RetrieveUserGroupResp) GetUpdateAt() int64 {
	if x != nil {
		return x.UpdateAt
	}
	return 0
}

// 更新用户组传入参数
type UpdateUserGroupReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserGroup *RetrieveUserGroupResp `protobuf:"bytes,1,opt,name=userGroup,proto3" json:"userGroup,omitempty"`
}

func (x *UpdateUserGroupReq) Reset() {
	*x = UpdateUserGroupReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_user_rpc_proto_userGroup_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUserGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserGroupReq) ProtoMessage() {}

func (x *UpdateUserGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_user_rpc_proto_userGroup_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserGroupReq.ProtoReflect.Descriptor instead.
func (*UpdateUserGroupReq) Descriptor() ([]byte, []int) {
	return file_common_user_rpc_proto_userGroup_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateUserGroupReq) GetUserGroup() *RetrieveUserGroupResp {
	if x != nil {
		return x.UserGroup
	}
	return nil
}

// 更新用户组返回参数
type UpdateUserGroupResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"` // 用户组ID
}

func (x *UpdateUserGroupResp) Reset() {
	*x = UpdateUserGroupResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_user_rpc_proto_userGroup_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUserGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserGroupResp) ProtoMessage() {}

func (x *UpdateUserGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_common_user_rpc_proto_userGroup_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserGroupResp.ProtoReflect.Descriptor instead.
func (*UpdateUserGroupResp) Descriptor() ([]byte, []int) {
	return file_common_user_rpc_proto_userGroup_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUserGroupResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 删除用户组传入参数
type DeleteUserGroupReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"` // 用户组ID
}

func (x *DeleteUserGroupReq) Reset() {
	*x = DeleteUserGroupReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_user_rpc_proto_userGroup_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserGroupReq) ProtoMessage() {}

func (x *DeleteUserGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_user_rpc_proto_userGroup_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserGroupReq.ProtoReflect.Descriptor instead.
func (*DeleteUserGroupReq) Descriptor() ([]byte, []int) {
	return file_common_user_rpc_proto_userGroup_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteUserGroupReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 删除用户组返回参数
type DeleteUserGroupResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"` // 用户组ID
}

func (x *DeleteUserGroupResp) Reset() {
	*x = DeleteUserGroupResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_user_rpc_proto_userGroup_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteUserGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserGroupResp) ProtoMessage() {}

func (x *DeleteUserGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_common_user_rpc_proto_userGroup_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserGroupResp.ProtoReflect.Descriptor instead.
func (*DeleteUserGroupResp) Descriptor() ([]byte, []int) {
	return file_common_user_rpc_proto_userGroup_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteUserGroupResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 查询用户组参数
type QueryUserGroupReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids         []int64              `protobuf:"varint,1,rep,packed,name=Ids,proto3" json:"Ids,omitempty"`                            // 多个用户组ID
	Name        string               `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`                                  // 用户组名称
	ParentId    []int64              `protobuf:"varint,3,rep,packed,name=ParentId,proto3" json:"ParentId,omitempty"`                  // 父组ID
	IsAdmin     proto.BoolSelectEnum `protobuf:"varint,4,opt,name=IsAdmin,proto3,enum=proto.BoolSelectEnum" json:"IsAdmin,omitempty"` // 是否管理员
	CreateUser  int64                `protobuf:"varint,5,opt,name=CreateUser,proto3" json:"CreateUser,omitempty"`                     // 创建用户ID（查询此用户创建的所有用户组）
	UpdateUser  int64                `protobuf:"varint,6,opt,name=UpdateUser,proto3" json:"UpdateUser,omitempty"`                     // 更新用户ID（查询此用户更新过的用户组）
	CreateGroup int64                `protobuf:"varint,7,opt,name=CreateGroup,proto3" json:"CreateGroup,omitempty"`                   // 创建用户组ID（查询此用户组创建的所有用户组）
	UpdateGroup int64                `protobuf:"varint,8,opt,name=UpdateGroup,proto3" json:"UpdateGroup,omitempty"`                   // 更新用户组ID（查询此用户组更新的所有用户组）
	CreateAt    []int64              `protobuf:"varint,9,rep,packed,name=CreateAt,proto3" json:"CreateAt,omitempty"`                  // 创建时间
	UpdateAt    []int64              `protobuf:"varint,10,rep,packed,name=UpdateAt,proto3" json:"UpdateAt,omitempty"`                 // 更新时间
}

func (x *QueryUserGroupReq) Reset() {
	*x = QueryUserGroupReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_user_rpc_proto_userGroup_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryUserGroupReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUserGroupReq) ProtoMessage() {}

func (x *QueryUserGroupReq) ProtoReflect() protoreflect.Message {
	mi := &file_common_user_rpc_proto_userGroup_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUserGroupReq.ProtoReflect.Descriptor instead.
func (*QueryUserGroupReq) Descriptor() ([]byte, []int) {
	return file_common_user_rpc_proto_userGroup_proto_rawDescGZIP(), []int{8}
}

func (x *QueryUserGroupReq) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *QueryUserGroupReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueryUserGroupReq) GetParentId() []int64 {
	if x != nil {
		return x.ParentId
	}
	return nil
}

func (x *QueryUserGroupReq) GetIsAdmin() proto.BoolSelectEnum {
	if x != nil {
		return x.IsAdmin
	}
	return proto.BoolSelectEnum(0)
}

func (x *QueryUserGroupReq) GetCreateUser() int64 {
	if x != nil {
		return x.CreateUser
	}
	return 0
}

func (x *QueryUserGroupReq) GetUpdateUser() int64 {
	if x != nil {
		return x.UpdateUser
	}
	return 0
}

func (x *QueryUserGroupReq) GetCreateGroup() int64 {
	if x != nil {
		return x.CreateGroup
	}
	return 0
}

func (x *QueryUserGroupReq) GetUpdateGroup() int64 {
	if x != nil {
		return x.UpdateGroup
	}
	return 0
}

func (x *QueryUserGroupReq) GetCreateAt() []int64 {
	if x != nil {
		return x.CreateAt
	}
	return nil
}

func (x *QueryUserGroupReq) GetUpdateAt() []int64 {
	if x != nil {
		return x.UpdateAt
	}
	return nil
}

// 查询用户组返回参数
type QueryUserGroupResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserGroup []*RetrieveUserGroupResp `protobuf:"bytes,1,rep,name=UserGroup,proto3" json:"UserGroup,omitempty"` // 多条用户详细信息
}

func (x *QueryUserGroupResp) Reset() {
	*x = QueryUserGroupResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_user_rpc_proto_userGroup_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryUserGroupResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUserGroupResp) ProtoMessage() {}

func (x *QueryUserGroupResp) ProtoReflect() protoreflect.Message {
	mi := &file_common_user_rpc_proto_userGroup_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUserGroupResp.ProtoReflect.Descriptor instead.
func (*QueryUserGroupResp) Descriptor() ([]byte, []int) {
	return file_common_user_rpc_proto_userGroup_proto_rawDescGZIP(), []int{9}
}

func (x *QueryUserGroupResp) GetUserGroup() []*RetrieveUserGroupResp {
	if x != nil {
		return x.UserGroup
	}
	return nil
}

var File_common_user_rpc_proto_userGroup_proto protoreflect.FileDescriptor

var file_common_user_rpc_proto_userGroup_proto_rawDesc = []byte{
	0x0a, 0x25, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x72, 0x70,
	0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x75, 0x73, 0x65, 0x72, 0x1a, 0x17, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x44, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x25, 0x0a, 0x13,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x49, 0x64, 0x22, 0x26, 0x0a, 0x14, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x22, 0xc1, 0x02, 0x0a, 0x15,
	0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x50, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x73, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x49, 0x73, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x44, 0x65, 0x73, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44,
	0x65, 0x73, 0x63, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x20, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x41, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x41, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x74, 0x22,
	0x4f, 0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x52, 0x65, 0x71, 0x12, 0x39, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e,
	0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x52, 0x09, 0x75, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x22, 0x25, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x22, 0x24, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x22, 0x25, 0x0a,
	0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x49, 0x64, 0x22, 0xc2, 0x02, 0x0a, 0x11, 0x51, 0x75, 0x65, 0x72, 0x79, 0x55, 0x73,
	0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x49, 0x64,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x03, 0x49, 0x64, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x03, 0x52, 0x08, 0x50, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x07,
	0x49, 0x73, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6f, 0x6f, 0x6c, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x45, 0x6e, 0x75, 0x6d, 0x52, 0x07, 0x49, 0x73, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x1e, 0x0a,
	0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1e, 0x0a,
	0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x20, 0x0a,
	0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12,
	0x20, 0x0a, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x09, 0x20,
	0x03, 0x28, 0x03, 0x52, 0x08, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x74, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x08, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x74, 0x22, 0x4f, 0x0a, 0x12, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x39, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65,
	0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x52,
	0x09, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x32, 0xc9, 0x02, 0x0a, 0x09, 0x55,
	0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x3d, 0x0a, 0x06, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x12, 0x18, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72,
	0x6f, 0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3d, 0x0a, 0x06, 0x75, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x18, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3d, 0x0a, 0x06, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x12, 0x18, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3a, 0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x12, 0x17,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x51, 0x75, 0x65, 0x72, 0x79, 0x55, 0x73, 0x65, 0x72, 0x47,
	0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x18, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x43, 0x0a, 0x08, 0x72, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x12, 0x1a, 0x2e,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x55, 0x73, 0x65, 0x72, 0x47, 0x72, 0x6f,
	0x75, 0x70, 0x52, 0x65, 0x73, 0x70, 0x42, 0x1e, 0x5a, 0x1c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b,
	0x75, 0x73, 0x65, 0x72, 0x50, 0x42, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_user_rpc_proto_userGroup_proto_rawDescOnce sync.Once
	file_common_user_rpc_proto_userGroup_proto_rawDescData = file_common_user_rpc_proto_userGroup_proto_rawDesc
)

func file_common_user_rpc_proto_userGroup_proto_rawDescGZIP() []byte {
	file_common_user_rpc_proto_userGroup_proto_rawDescOnce.Do(func() {
		file_common_user_rpc_proto_userGroup_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_user_rpc_proto_userGroup_proto_rawDescData)
	})
	return file_common_user_rpc_proto_userGroup_proto_rawDescData
}

var file_common_user_rpc_proto_userGroup_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_common_user_rpc_proto_userGroup_proto_goTypes = []interface{}{
	(*CreateUserGroupReq)(nil),    // 0: user.CreateUserGroupReq
	(*CreateUserGroupResp)(nil),   // 1: user.CreateUserGroupResp
	(*RetrieveUserGroupReq)(nil),  // 2: user.RetrieveUserGroupReq
	(*RetrieveUserGroupResp)(nil), // 3: user.RetrieveUserGroupResp
	(*UpdateUserGroupReq)(nil),    // 4: user.UpdateUserGroupReq
	(*UpdateUserGroupResp)(nil),   // 5: user.UpdateUserGroupResp
	(*DeleteUserGroupReq)(nil),    // 6: user.DeleteUserGroupReq
	(*DeleteUserGroupResp)(nil),   // 7: user.DeleteUserGroupResp
	(*QueryUserGroupReq)(nil),     // 8: user.QueryUserGroupReq
	(*QueryUserGroupResp)(nil),    // 9: user.QueryUserGroupResp
	(proto.BoolSelectEnum)(0),     // 10: proto.BoolSelectEnum
}
var file_common_user_rpc_proto_userGroup_proto_depIdxs = []int32{
	3,  // 0: user.UpdateUserGroupReq.userGroup:type_name -> user.RetrieveUserGroupResp
	10, // 1: user.QueryUserGroupReq.IsAdmin:type_name -> proto.BoolSelectEnum
	3,  // 2: user.QueryUserGroupResp.UserGroup:type_name -> user.RetrieveUserGroupResp
	0,  // 3: user.UserGroup.create:input_type -> user.CreateUserGroupReq
	4,  // 4: user.UserGroup.update:input_type -> user.UpdateUserGroupReq
	6,  // 5: user.UserGroup.delete:input_type -> user.DeleteUserGroupReq
	8,  // 6: user.UserGroup.query:input_type -> user.QueryUserGroupReq
	2,  // 7: user.UserGroup.retrieve:input_type -> user.RetrieveUserGroupReq
	1,  // 8: user.UserGroup.create:output_type -> user.CreateUserGroupResp
	5,  // 9: user.UserGroup.update:output_type -> user.UpdateUserGroupResp
	7,  // 10: user.UserGroup.delete:output_type -> user.DeleteUserGroupResp
	9,  // 11: user.UserGroup.query:output_type -> user.QueryUserGroupResp
	3,  // 12: user.UserGroup.retrieve:output_type -> user.RetrieveUserGroupResp
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_common_user_rpc_proto_userGroup_proto_init() }
func file_common_user_rpc_proto_userGroup_proto_init() {
	if File_common_user_rpc_proto_userGroup_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_user_rpc_proto_userGroup_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserGroupReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_user_rpc_proto_userGroup_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserGroupResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_user_rpc_proto_userGroup_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveUserGroupReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_user_rpc_proto_userGroup_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RetrieveUserGroupResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_user_rpc_proto_userGroup_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUserGroupReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_user_rpc_proto_userGroup_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUserGroupResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_user_rpc_proto_userGroup_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUserGroupReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_user_rpc_proto_userGroup_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteUserGroupResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_user_rpc_proto_userGroup_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryUserGroupReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_user_rpc_proto_userGroup_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryUserGroupResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_user_rpc_proto_userGroup_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_user_rpc_proto_userGroup_proto_goTypes,
		DependencyIndexes: file_common_user_rpc_proto_userGroup_proto_depIdxs,
		MessageInfos:      file_common_user_rpc_proto_userGroup_proto_msgTypes,
	}.Build()
	File_common_user_rpc_proto_userGroup_proto = out.File
	file_common_user_rpc_proto_userGroup_proto_rawDesc = nil
	file_common_user_rpc_proto_userGroup_proto_goTypes = nil
	file_common_user_rpc_proto_userGroup_proto_depIdxs = nil
}
