// protoc --go_out=. --go-grpc_out=require_unimplemented_servers=false:. ./common/user/rpc/proto/*.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: common/user/rpc/proto/userGroup.proto

package userPB

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	UserGroup_Create_FullMethodName   = "/user.UserGroup/create"
	UserGroup_Update_FullMethodName   = "/user.UserGroup/update"
	UserGroup_Delete_FullMethodName   = "/user.UserGroup/delete"
	UserGroup_Query_FullMethodName    = "/user.UserGroup/query"
	UserGroup_Retrieve_FullMethodName = "/user.UserGroup/retrieve"
)

// UserGroupClient is the client API for UserGroup service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserGroupClient interface {
	Create(ctx context.Context, in *CreateUserGroupReq, opts ...grpc.CallOption) (*CreateUserGroupResp, error)
	Update(ctx context.Context, in *UpdateUserGroupReq, opts ...grpc.CallOption) (*UpdateUserGroupResp, error)
	Delete(ctx context.Context, in *DeleteUserGroupReq, opts ...grpc.CallOption) (*DeleteUserGroupResp, error)
	Query(ctx context.Context, in *QueryUserGroupReq, opts ...grpc.CallOption) (*QueryUserGroupResp, error)
	Retrieve(ctx context.Context, in *RetrieveUserGroupReq, opts ...grpc.CallOption) (*RetrieveUserGroupResp, error)
}

type userGroupClient struct {
	cc grpc.ClientConnInterface
}

func NewUserGroupClient(cc grpc.ClientConnInterface) UserGroupClient {
	return &userGroupClient{cc}
}

func (c *userGroupClient) Create(ctx context.Context, in *CreateUserGroupReq, opts ...grpc.CallOption) (*CreateUserGroupResp, error) {
	out := new(CreateUserGroupResp)
	err := c.cc.Invoke(ctx, UserGroup_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userGroupClient) Update(ctx context.Context, in *UpdateUserGroupReq, opts ...grpc.CallOption) (*UpdateUserGroupResp, error) {
	out := new(UpdateUserGroupResp)
	err := c.cc.Invoke(ctx, UserGroup_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userGroupClient) Delete(ctx context.Context, in *DeleteUserGroupReq, opts ...grpc.CallOption) (*DeleteUserGroupResp, error) {
	out := new(DeleteUserGroupResp)
	err := c.cc.Invoke(ctx, UserGroup_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userGroupClient) Query(ctx context.Context, in *QueryUserGroupReq, opts ...grpc.CallOption) (*QueryUserGroupResp, error) {
	out := new(QueryUserGroupResp)
	err := c.cc.Invoke(ctx, UserGroup_Query_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userGroupClient) Retrieve(ctx context.Context, in *RetrieveUserGroupReq, opts ...grpc.CallOption) (*RetrieveUserGroupResp, error) {
	out := new(RetrieveUserGroupResp)
	err := c.cc.Invoke(ctx, UserGroup_Retrieve_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserGroupServer is the server API for UserGroup service.
// All implementations should embed UnimplementedUserGroupServer
// for forward compatibility
type UserGroupServer interface {
	Create(context.Context, *CreateUserGroupReq) (*CreateUserGroupResp, error)
	Update(context.Context, *UpdateUserGroupReq) (*UpdateUserGroupResp, error)
	Delete(context.Context, *DeleteUserGroupReq) (*DeleteUserGroupResp, error)
	Query(context.Context, *QueryUserGroupReq) (*QueryUserGroupResp, error)
	Retrieve(context.Context, *RetrieveUserGroupReq) (*RetrieveUserGroupResp, error)
}

// UnimplementedUserGroupServer should be embedded to have forward compatible implementations.
type UnimplementedUserGroupServer struct {
}

func (UnimplementedUserGroupServer) Create(context.Context, *CreateUserGroupReq) (*CreateUserGroupResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedUserGroupServer) Update(context.Context, *UpdateUserGroupReq) (*UpdateUserGroupResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedUserGroupServer) Delete(context.Context, *DeleteUserGroupReq) (*DeleteUserGroupResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedUserGroupServer) Query(context.Context, *QueryUserGroupReq) (*QueryUserGroupResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedUserGroupServer) Retrieve(context.Context, *RetrieveUserGroupReq) (*RetrieveUserGroupResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Retrieve not implemented")
}

// UnsafeUserGroupServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserGroupServer will
// result in compilation errors.
type UnsafeUserGroupServer interface {
	mustEmbedUnimplementedUserGroupServer()
}

func RegisterUserGroupServer(s grpc.ServiceRegistrar, srv UserGroupServer) {
	s.RegisterService(&UserGroup_ServiceDesc, srv)
}

func _UserGroup_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGroupServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserGroup_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGroupServer).Create(ctx, req.(*CreateUserGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserGroup_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGroupServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserGroup_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGroupServer).Update(ctx, req.(*UpdateUserGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserGroup_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGroupServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserGroup_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGroupServer).Delete(ctx, req.(*DeleteUserGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserGroup_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUserGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGroupServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserGroup_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGroupServer).Query(ctx, req.(*QueryUserGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserGroup_Retrieve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveUserGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserGroupServer).Retrieve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserGroup_Retrieve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserGroupServer).Retrieve(ctx, req.(*RetrieveUserGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserGroup_ServiceDesc is the grpc.ServiceDesc for UserGroup service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserGroup_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserGroup",
	HandlerType: (*UserGroupServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "create",
			Handler:    _UserGroup_Create_Handler,
		},
		{
			MethodName: "update",
			Handler:    _UserGroup_Update_Handler,
		},
		{
			MethodName: "delete",
			Handler:    _UserGroup_Delete_Handler,
		},
		{
			MethodName: "query",
			Handler:    _UserGroup_Query_Handler,
		},
		{
			MethodName: "retrieve",
			Handler:    _UserGroup_Retrieve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "common/user/rpc/proto/userGroup.proto",
}
